version: '2'

services:
  postgresql:
    container_name: postgresqlProd
    build: ./
    ports:
      - "9032:5432"
    network_mode: bridge
#    volumes:
#      - "./data/db:/var/lib/postgresql/data"
#       - "./init/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_DB=db_volontario
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
